### PR TITLE
onSlidingStart prop

### PR DESCRIPTION
**Pull request by chakrihacker**
Added onSlidingStartProp

### CODE REVIEW

**Comment by chakrihacker** [comment]
closes #37

**Comment by michalchudziak** [comment]
Great job, thanks a lot!

I'm in the middle of testing your change on a device. If everything succeeds, I'm going to merge it.

**Comment by chakrihacker** [comment]
Let me refactor iOS code

**Comment by michalchudziak** [comment]
Yeah, it might be a good idea! Generally, it works great, but adding `isSlidingStart` as a param to `RNCSendSliderEvent` looks a bit unclear. Perhaps you have a different idea on how to approach that. I'm waiting for your changes and I'll review it.

Thanks a lot, I really appreciate your approach!

**Comment by chakrihacker** [comment]
Hi 👋, any iOS experts? 🤔

I need help refactoring this.

**Comment by michalchudziak** [comment]
@chakrihacker I'll handle that from this point, thank you. You did great!

**Comment by chakrihacker** [comment]
👍

**Pull request merged**
