### PR TITLE
[web] Added browser support

### PR DESCRIPTION
**Pull request by EvanBacon**
Summary:
---------

Added web support. https://github.com/necolas/react-native-web/issues/1022 

Wanted to keep this PR simple in order to get React Native Gesture Handler working as expected.

CC: @necolas

Test Plan:
----------

[Try it here](https://rnslider.netlify.com/)

### CODE REVIEW

**Comment by necolas** [comment]
A web implementation would need to include screen reader and keyboard support. Might be better to use the native controls under the hood. I'd also ditch heavy dependencies like Animated.

**Comment by saru2020** [comment]
Any idea when this would be ready/merged?

**Comment by jorgechen** [comment]
Somebody please lift this out of dev hell 🙏

**Comment by gianpaj** [comment]
This works really well!

Jan-29-2020 23-16-15

```jsx
import debounce from 'lodash.debounce';

const [distance, setDistance] = useState(10);

<Slider
  value={distance}
  style={{
    marginHorizontal: 10,
    height: 40,
    width: 180,
  }}
  minimumValue={0}
  maximumValue={1000}
  minimumTrackTintColor="#b4d334"
  thumbTintColor="#b4d334"
  maximumTrackTintColor="#000000"
  step={100}
  onValueChange={debounce(setDistance, 10)}
/>
```

PS: I had to add debounce otherwise it would be super slow.

**Comment by michalchudziak** [comment]
If anyone could pick it up I'd love to merge that one!

**Comment by JesseRWeigel** [comment]
@michalchudziak I would like to pick this up. Based on circleci, it looks like the only issues were flow errors. Is that correct?

**Comment by Sharcoux** [comment]
Why not using an input range instead of reinventing the wheel?

**Comment by Sharcoux** [comment]
I allowed myself to propose [this implementation](https://github.com/react-native-community/react-native-slider/pull/165)

**Comment by michalchudziak** [comment]
I'm sorry to close this PR, as most of the work was already complete, although I haven't heard back from the author and the PR is in the draft state. I think we are going to merge https://github.com/react-native-community/react-native-slider/pull/165/files as we've waited for a long time, and the implementation in the linked PR seems to be complete.

**Comment by michalchudziak** [comment]
@Sharcoux I've tested your implementation and it seems like that one is working better, how about merging https://github.com/react-native-community/react-native-slider/pull/165/files with this PR? I'd like to credit both of you :) Thanks for the contributions!

**Comment by Sharcoux** [comment]
@michalchudziak is the fix I proposed in the last commit fine for you or is there something alse bothering you?

In this PR, I'm concerned about the comment about @gianpaj mentionning the need of debounce. I'm also wondering if the Animated API won't generate performance issues. I'm wondering also how the import might work if there is no build step when publishing, but tell me if I'm wrong.

**Comment by necolas** [comment]
Neither implementation is accessible at the moment. Using animated requires a lot more JS to be downloaded and run, which is not great for performance either

**Comment by Sharcoux** [comment]
@necolas good remark. So for web the thumb should be focusable and receive arrows events, is that it?

**Comment by necolas** [comment]
It also needs aria markup. I don't have time to research everything that's needed right now

**Comment by Sharcoux** [comment]
Ok, I'll check it and add that. Thanks for letting me know about aria.

**Comment by Sharcoux** [comment]
@necolas I implemented the accessibility on @sharcoux/slider version 2.0.12
Could you try it out and tell me if it seems fine for you ?

**Comment by Sharcoux** [comment]
My bad, I did some shit. Let me fix that.

**Comment by Sharcoux** [comment]
Ok, @necolas version 2.0.15 should be accessible. Check there please: https://snack.expo.io/MqyqPrdMT

**Comment by EvanBacon** [comment]
Closing now that it's merged elsewhere. I'll work on the example if I have time.

**Pull request closed without merging**
